apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: threatmap-kafka-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: threatmap-backend-kafka-secret
  data:
    - secretKey: password
      remoteRef:
        key: kafka/threatmap
        property: password
