apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: attack-events
  labels:
    strimzi.io/cluster: cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "86400000"
    cleanup.policy: delete
