apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluentd-kafka-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fluentd-kafka-secret
  data:
    - secretKey: username
      remoteRef:
        key: kafka/threatmap
        property: username
    - secretKey: password
      remoteRef:
        key: kafka/threatmap
        property: password
