apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: threatmap-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: threatmap-secrets
  data:
  - secretKey: OTX_API_KEY
    remoteRef:
      key: threatmap/otx
      property: otx_api_key
  - secretKey: MAXMIND_LICENSE_KEY
    remoteRef:
      key: threatmap/maxmind
      property: license_key
  - secretKey: password
    remoteRef:
      key: threatmap/mongodb
      property: password
  - secretKey: KAFKA_USERNAME
    remoteRef:
      key: kafka/threatmap
      property: username
  - secretKey: KAFKA_PASSWORD
    remoteRef:
      key: kafka/threatmap
      property: password
