apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threatmap
resources:
  - ns.yaml
  - externalsecret.yaml
  - mongodb-rbac.yaml
  - mongodb.yaml
  - backend.yaml
  - frontend.yaml
  - httproute.yaml
