services:
  ansible-runner:
    image: ansible-runner
    build:
      context: ..
      dockerfile: ansible-runner/Dockerfile
    container_name: ansible-runner
    restart: unless-stopped
    environment:
      ANSIBLE_PRIVATE_KEY_FILE: /home/runner/.ssh/id_rsa
    volumes:
      - ./../ansible:/ansible
      - ./../kubernetes:/kubernetes
      - ./../terraform:/terraform
      - ./../metal/x86/pxe-files:/metal/x86/pxe-files
      - ${HOME}/.secrets:/home/runner/.secrets
      - ${HOME}/.ssh:/home/runner/.ssh_host:ro
      - ${HOME}/.kube:/home/runner/.kube
      - ${HOME}/.certbot/log:/home/runner/.certbot/log
      - ${HOME}/.certbot/config:/home/runner/.certbot/config
      - ${HOME}/.certbot/work:/home/runner/.certbot/work
    entrypoint: >
      /bin/bash -c "
      mkdir -p /home/runner/.ssh &&
      cp /home/runner/.ssh_host/id_rsa /home/runner/.ssh/id_rsa &&
      cp /home/runner/.ssh_host/id_rsa.pub /home/runner/.ssh/id_rsa.pub &&
      chmod 600 /home/runner/.ssh/id_rsa &&
      chmod 644 /home/runner/.ssh/id_rsa.pub &&
      tail -f /dev/null
      "
    user: runner
